import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { faCalendar } from '@fortawesome/free-regular-svg-icons'
import {
    faArrowLeft,
    faArrowRight,
    faArrowUpRightFromSquare,
    faBolt,
    faBorderAll,
    faBoxArchive,
    faBoxOpen,
    faBuildingColumns,
    faBullseye,
    faChartLine,
    faChartPie,
    faCheck,
    faCircleCheck,
    faCircleExclamation,
    faCircleInfo,
    faCloudSun,
    faCoins,
    faCreditCard,
    faDatabase,
    faFileCirclePlus,
    faFileCircleQuestion,
    faFileShield,
    faHashtag,
    faMagnifyingGlass,
    faMagnifyingGlassChart,
    faMoneyCheckDollar,
    faPenToSquare,
    faPlus,
    faReceipt,
    faSignal,
    faSpinner,
    faTriangleExclamation,
    faWallet,
    faWaveSquare,
} from '@fortawesome/free-solid-svg-icons'

library.add(
    faCalendar,
    faArrowLeft,
    faArrowRight,
    faArrowUpRightFromSquare,
    faBolt,
    faBorderAll,
    faBoxArchive,
    faBoxOpen,
    faBuildingColumns,
    faBullseye,
    faChartLine,
    faChartPie,
    faCheck,
    faCircleCheck,
    faCircleExclamation,
    faCircleInfo,
    faCloudSun,
    faCoins,
    faCreditCard,
    faDatabase,
    faFileCirclePlus,
    faFileCircleQuestion,
    faFileShield,
    faHashtag,
    faMagnifyingGlass,
    faMagnifyingGlassChart,
    faMoneyCheckDollar,
    faPenToSquare,
    faPlus,
    faReceipt,
    faSignal,
    faSpinner,
    faTriangleExclamation,
    faWallet,
    faWaveSquare
)

createApp(App).use(store).use(router).component('font-awesome-icon', FontAwesomeIcon).mount('#app')
